spring.datasource.url=jdbc:postgresql://ep-weathered-union-an4tapmq-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tecRNPIG4mS9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akremizayneb99@gmail.com
spring.mail.password=olxt usll hxvw msok
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret=Ins0mea@CRM#2026$SecureKey!XyZ147
jwt.expiration=86400000
jwt.expiration.remember=2592000000

server.port=8081
